### ISSUE TITLE
TuxGuitar doesn't pick up Win10's theme settings (dark theme)

### ISSUE THREAD

**Issue by kainah** [helge17/tuxguitar#27]
It seems that on the latest snapshot as of now (2023-05-02) neither the SWT, nor the JavaFX (Qt5) versions can change the style based on Windows (10, at least) settings. So the app uses the light style instead, which looks out of place. 
I would expect that from SWT, but since JavaFX is tied to Qt libraries, I think it might be possible to link the styles in TuxGuitar and Win somehow.
Helgar @helge17 mentioned that TuxGuitar can actually pick up *nix style settings (he uses KDE).
Not a big deal, but maybe it's worth looking into, if possible.

Also, JavaFX under Win10 even looks worse than the SWT version, too much space wasted everywhere. But I think it would be manageable if TuxGuitar had any working style settings beside the icon theme.
(or if there was an utility to system-wide edit the Qt5 style, but I'm not sure if there is any way to change those settings on Win)

I'm attaching both SWT and JavaFX (Qt5) versions screenshots.

![Qt5](https://user-images.githubusercontent.com/1732918/236128200-c381e36c-e6ee-48a4-8b3a-b202a778b6bb.png)

![SWT](https://user-images.githubusercontent.com/1732918/236128262-1f3fcde4-a34d-4648-a0e2-0ff5c17889b3.png)

**Comment by guiv42** [comment]
I'm not sure I have fully understood the description of this issue, but fore sure there is a problem about themes, and not only in Windows configuration. I'm running Linux (OpenSuse tumbleweed / KDE), and selection of "Oxygen-dark" theme switches only the foreground color of icons in the tools panel, *not* the background color. White icons on top of a clear grey background... it's just unusable!
See screenshots: 1st is Oxygen, 2nd is Oxygen-dark
![Oxygen](https://user-images.githubusercontent.com/129443524/236872187-904c51c7-42da-49b7-9263-e54bca44605c.png)
![Oxygen_dark](https://user-images.githubusercontent.com/129443524/236872200-9e0809d0-50c9-48f9-b227-9c3c7db0a161.png)

**Comment by helge17** [comment]
The icon set in "Oxygen-dark" is for when you put your desktop in dark mode, but it doesn't turn dark mode on automatically.

So you have to switch your KDE to dark mode first, then TuxGuitar will be black too (same on macOS). Now you can select the "Oxygen-dark" theme to see the light icons on the dark background. I added a dark preview a few days ago, see https://github.com/helge17/tuxguitar/blob/master/TuxGuitar/share/skins/Oxygen-dark/skin-preview.png .

But the dark mode has some problems, for example:
- You have to restart TuxGuitar to apply the dark settings completely.
- You have to manually select the appropriate "Oxygen-dark" theme (e.g. LibreOffice automatically selects light icons in dark mode).
- TuxGuitar completely ignores the dark mode settings in Windows, it just stays bright.

**Comment by guiv42** [comment]
an interesting project:
https://github.com/Dansoftowner/jSystemThemeDetector

**Comment by guiv42** [comment]
Two different things needed to make dark mode work correctly

1. Background color
With the exception of the tablature itself, background color of all graphical elements (menus, dialogs, buttons, toolbar, etc.) is defined by SWT. Not by TuxGuitar code. So until SWT can handle properly the Windows dark mode, unfortunately I think there's nothing we can do.

2. Foreground color
Foreground color of text (menu items, buttons, etc.) is also defined by SWT. Same issue as background color.
Foreground color of buttons *is* defined by TuxGuitar, in the different skins.
We could imagine to detect dynamically if current mode is bright/dark, and switch skin accordingly. While I think this could be done currently in Linux/macOS environment, it's not possible in Windows.

**Comment by HaegarTheHorrible** [comment]
Is there no easy fix? Having a bright and white app, while everything else is dark themed, is killing me.

**Comment by guiv42** [comment]
@HaegarTheHorrible: sorry, if there was an easy fix this would have been implemented already! (this issue is more than 1 year old)
See my analysis (updated this week): I do believe this problem is an Eclipse SWT issue. If I'm right I think there's just nothing I can do :(

**Comment by guiv42** [comment]
Here is a summary of my attempts to progress on this issue. Any help would be greatly appreciated.

1. Detect desktop config (light/dark)

This could be used to select automatically the correct variant of a skin available in both bright & dark versions.
Simply reading a registry key as implemented [here](https://github.com/Dansoftowner/jSystemThemeDetector/blob/ea2f8582ea08cd53f221b09930956f539e771d69/src/main/java/com/jthemedetecor/WindowsThemeDetector.java#L50) works fine in my Win config (Win 10 family v1809). From what I read it may not be reliable with Win11, but I cannot test.
I did not investigate any method for Linux/macOS/freeBSD.

2. Apply dark background to SWT widgets

It's frustrating, there are many examples in SWT doc showing Win screenshots with dark background.
Something to try: build a "Hello world" app with SWT, to see if it works, then investigate if issue could be created by TuxGuitar's UI abstraction layer.

I tried a few things found on the Internet. Tests KO (no visual impact):
- https://davy.ai/how-to-get-swt-jface-stand-alone-app-to-render-ui-in-dark-mode/
- devcodef1.com/news/1121539/dark-theme-in-swt-apps-win10-11 (no hyperlink here it's intentional: I get "unappropriate" popups on this site...)
- switch to latest version of SWT for Windows (4.33)

Some interesting results:
- first code snippet from [this page](https://www.eclipse.org/forums/index.php/t/1113122/) leads to dark *decoration of windows* (main window, dialogs). Content of windows remains unchanged.
  Using reflection looks like a dirty hack, but it could probably be implemented without reflection in a Win-specific plugin in TG.
- From [this page](https://stackoverflow.com/questions/59134664/how-to-use-java-swt-setbackground-method#59134778): I modified properties of `Shell` object in `SWTWindow` class constructor. It changes background of *some* items (toolbars, dialogs), but *not all* (buttons, menu items, drop-down lists, ...). I did not try anything to change foreground colors, so it leads to something visually inconsistent.

Combining these 2 changes, here is an example with pure black background (probably a bad idea)
![test](https://github.com/user-attachments/assets/20e43e02-d10b-4ec8-b00e-418ddf6df5d9)

**Comment by LargeUselessness** [comment]
recently find a stupid workaround if someone neeed it- ctrl+win+c invert the whole screen's color. this is window's function so it won't be too much of a problem

**Comment by re1sub** [comment]
So, weirdly I have the same exact behaviour for the theme whether Linux (Arch, KDE Plasma 6, Wayland) or Windows. I installed tuxguitar on Linux from AUR, the latest 2.0.1-1 version and noticed that the Skins only change the icons and not the colors of the elements. I fixed it by passing a GTH_THEME hint:

```bash
GTK_THEME=Adwaita:dark tuxguitar
```

Worked perfectly.

Couldn't find a solution on Windows, though. I used this one app called "Dark Mode Any App" and it did *something*, it did change colors but those colors weren't related to any theme and it was just a bad experience

**Comment by WolfVantage** [comment]
Windows 10 22H2 OS Build 19045.7548 - Dark modes still not working, my eyes still burning (dark mancave, 27 inch display = supernova) :(
