### ISSUE TITLE
Display tempo during playback in training mode

### ISSUE THREAD

**Issue by G-eos** [helge17/tuxguitar#345]
During playback in training mode, we can set the tempo to progress from a start value an end value. This is great feature. I would love to be able to see what is the current value of the tempo. Unfortunately I do not find where to display it.

**Comment by guiv42** [comment]
Just show player dialog: menu "View / show player" (or Ctrl+t), I've added the tempo here

**Comment by G-eos** [comment]
Thus, the display seems not correct on my Mac (if this is the good windows).
![image](https://github.com/helge17/tuxguitar/assets/1248414/a89b54b1-994d-40cc-aa26-eddcd5af6bec)

**Comment by guiv42** [comment]
Yes this is the right dialog, and this graphical representation is clearly unexpected. This is how it's supposed to look like, with the current tempo displayed in the top-left button (tempo is displayed only while playing):
![transport](https://github.com/helge17/tuxguitar/assets/129443524/cf545b91-8879-49f8-a792-8203c466fc02)

I've added the current tempo value last year (05/2023). Could you please check if the dialog has the correct aspect on mac in version 1.5.6 ? (the last version published on sourceforge)
Is the problem identical with other skins? (menu tools/settings -> skins tab)

**Comment by G-eos** [comment]
- Same with 1.5.6
- Changing skin to lavender fix the display. I test several themes all works fine.
- Going back to Oxygen fix it for him too.
Note, setting to Lavender, quit TuxGuitar. Then relaunch keep Lavender as theme. BUT display of tempo is truncated, changing to Oxygen fix it :), then going back to lavender is ok.

Thus, it seems, that if I start tuxguitar, I have the issue, changing the them fix it :)

**Comment by guiv42** [comment]
> Same with 1.5.6

This is good news somehow: at least I haven't introduced any regression :)
Then, I don't really have an explanation why it is fixed when skin is changed.

@G-eos : could you please do this (stupid) test?
start TuxGuitar, open dialog, close dialog and re-open it again

There is one known [SWT issue](https://github.com/eclipse-platform/eclipse.platform.swt/issues/568) in Linux context leading to incorrect dialog representation the first time it is displayed. I don't know if this could be similar in macOS context

**Comment by G-eos** [comment]
Hi ! Stupid test done, this is not related to the first dialog display. Even time the dialog is opened it is the same truncated.

**Comment by G-eos** [comment]
Now, still with 1.5.6 and with the latest version compiled by myself from GitHub. The behavior changes ...
Command-t (or directly from the menu) the dialog is never the good size ... Changing themes does not solve it !

I do not change things, no OS update. Only a Reboot ... there is for sure that someting changes :)

**Comment by guiv42** [comment]
I don't like these non-reproducible issues :(
Is this the only dialog in TuxGuitar with this kind of problem?

@G-eos, just a suggestion, since the topic discussed here is no more aligned with issue's description: close this issue, and open another one (bug, specific to macOS) about the incorrect display of player dialog.
If that's OK for you, please precise in this new issue the different test sequences performed and their results, and the description of your config (macOS version, TuxGuitar version(s)).
